# Configuración de Servidor
server.port=8080

# Configuración de Base de Datos - VE ABSOLUTA [cite: 22, 53]
spring.datasource.url=jdbc:postgresql://localhost:5432/ve_absoluta_db
spring.datasource.username=postgres
spring.datasource.password=TU_CONTRASEÑA
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' permite que Hibernate cree o ajuste tablas automáticamente si detecta cambios en tus clases Kotlin 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true